### ISSUE TITLE
Method to scroll element to center

### ISSUE THREAD

**Issue by rlebl21** [p0deje/watir-scroll#2]
Not sure if you can do this but I would like the ability to scroll to the element with the element being in the center of the page. Our app has an overlay and the default scroll leaves the element under the overlay and inaccessible.

**Comment by p0deje** [comment]
I'm thinking about the way API would work for it.

``` ruby
element.scroll # scroll element to top
element.scroll(:bottom) # scroll element to bottom
element.scroll(:centre) # scroll element to centre
```

What do you think?

**Comment by p0deje** [comment]
It is implemented in master as `element.scroll.to :center`, but I have to postpone release until Travis is green.

You can however try it by using master branch in `Gemfile`:

``` ruby
gem 'watir-scroll', github: 'p0deje/watir-scroll'
```

Closing this issue as it's fixed and will leave comment when it's released.

**Comment by p0deje** [comment]
Release in v0.2.0
