### ISSUE TITLE
Why watir-scroll does not work with watir-webdriver?

### ISSUE THREAD

**Issue by monkey-t** [p0deje/watir-scroll#4]
Why watir-scroll does not work with watir-webdriver?

"/home/user/.rvm/gems/ruby-2.3.1/gems/watir-6.1.0/lib/watir/wait.rb:8: warning: already initialized constant Watir::Wait::INTERVAL
/home/user/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.9/lib/watir-webdriver/wait.rb:9: warning: previous definition of INTERVAL was here
/home/user/.rvm/gems/ruby-2.3.1/gems/watir-6.1.0/lib/watir/atoms.rb:4: warning: already initialized constant Watir::Atoms::ATOMS
/home/user/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.9/lib/watir-webdriver/atoms.rb:4: warning: previous definition of ATOMS was here
/home/user/.rvm/gems/ruby-2.3.1/gems/watir-6.1.0/lib/watir/elements/html_elements.rb:951:in `<module:Container>': can't modify frozen Hash (RuntimeError)"

**Comment by p0deje** [comment]
Because "watir-webdriver" is no longer developed and is now "watir". In order to use recent version of watir-scroll, you need to migrate from watir-webdriver to watir 6.x.
